// xrplAddress.ts
export interface IExchangeAddress {
  name: string;     // Exchange name
  account: string;  // Exchange account
  desc: string;     // Description
};

export const exchangeAddresses : IExchangeAddress[] = [
  {name:"50x",account:"rQhNdbQpKL1rgrFKCyrqS6Er4nvu7dwWgi",desc:""},
  {name:"58 COIN",account:"rKSU67YATC7hJ8Y3CU4GKPBDhQYS2sQ5hG",desc:""},
  {name:"6X",account:"rPTRsvXTFfXiqoXsAj9nzNkyspUnosDNHi",desc:""},
  {name:"ABCC",account:"rPR82pZSV8xKWukAkvaoKKVn2W9eNBN97s",desc:""},
  {name:"Advanced Cash",account:"rMUThT2aBLHfNMSW92aHMaLUzgJVWomh26",desc:""},
  {name:"AEX",account:"rNdxqV8iU2eomFm186YkWUvNzoR9iyyEkR",desc:""},
  {name:"ALFAcashier",account:"rExFpwNwwrmFWbX81AqbHJYkq8W6ZoeWE6",desc:""},
  {name:"Allvor",account:"raEQc5krJ2rUXyi6fgmUAf63oAXmF7p6jp",desc:""},
  {name:"AlphaEx",account:"rhfzdZgZPTSqGVW41cwdfG4uudEhMwnd22",desc:""},
  {name:"Alterdice",account:"rdaSLGsDPV9YrtV5qe24isgXc4rwzr7dv",desc:""},
  {name:"Artis Turba",account:"rUZm6JF53B6QPPHCQG6J3GY6QekZqi5Gif",desc:""},
  {name:"Arwèn",account:"rPPnHiX69sHhYb9HE8BgZgcrCXbvk9baby",desc:""},
  {name:"B2BX",account:"rh1Qs81SBNLXzg1hQppVH53FDqfoE9NZFd",desc:""},
  {name:"BankCEX",account:"rpt26nftBYauVeeK9483WdaAUBpgWcN1LH",desc:""},
  {name:"Bankcomat",account:"r9UBpAtJFWRQbNbCXWjtV74HT8FA7nKwAr",desc:""},
  {name:"Blue Helix",account:"rNWLvz9K5bgNcLwUDPAKgnmfopZx3Svg3",desc:"BHEX"},
  {name:"Bibox",account:"rHZQVErv6UZTtkM4NVexS1Z5dTvuek2RbX",desc:"1"},
  {name:"Bibox",account:"rK3oET2H12t9a5fw766wE6pKuZMvKb3Y3n",desc:"2"},
  {name:"Biccos",account:"rh8GCypNXC3PwDHKWkwTYwuS3usd5mQiJ4",desc:"1"},
  {name:"Biccos",account:"rBnVQ2Db7TvB9AUQG3NFoioFE4qMcP6sEU",desc:"2"},
  {name:"BigONE",account:"ra8F9swTXUhBUCjjDUdWX8XiqNzFjrN2CW",desc:""},
  {name:"Biido",account:"raTuDcvwMebUwvJMrxAB64QCcNvxWeY9nv",desc:""},
  {name:"Biki",account:"r9hCYQF3WeENSu3KE2vjHXVzmw6B4CNbnX",desc:""},
  {name:"Bimax",account:"rLAwn4fTgmnQHJrRXb7g846TtF9AwCUZ2D",desc:"1"},
  {name:"Bimax",account:"rpXKcavHhGV9wpDwiricBTJE6pPuhKQqtT",desc:"2"},
  {name:"Binance",account:"rEb8TK3gBgk5auZkwc6sHnwrGVJH8DuaLh",desc:"1"},
  {name:"Binance",account:"rJb5KsHsDHF1YS5B5DU6QCkH5NsPaKQTcy",desc:"2"},
  {name:"Binance",account:"rEy8TFcrAPvhpKrwyrscNYyqBGUkE9hKaJ",desc:"3"},
  {name:"Birake",account:"rpD8gWASkS8p2ZnEFMpNZR1i9u71tsisz3",desc:""},
  {name:"bitbank",account:"rLbKbPyuvs4wc1h13BEPHgbFGsRXMeFGL6",desc:"1"},
  {name:"bitbank",account:"rw7m3CtVHwGSdhFjV4MyJozmZJv3DYQnsA",desc:"2"},
  {name:"bitbank",account:"rwggnsfxvCmDb3YP9Hs1TaGvrPR7ngrn7Z",desc:"3"},
  {name:"BitBay",account:"r9HwsqBnAUN4nF6nDqxd4sgP8DrDnDcZP3",desc:""},
  {name:"Bitbns",account:"r4VaPEKo4XoU27bCREgsTdbfKrKwNxJ1Cm",desc:""},
  {name:"Bitcoin mjenjačnica",account:"r6mh8tojcosU4WQg2R8Ggp38Y4ovWYkVA",desc:""},
  {name:"Bitexlive",account:"raGgLEtVHPrSgkL2YY6VQN2hGxDQd5QpEB",desc:""},
  {name:"BITEXBOOK",account:"rNQsy5WZCVnmedd4CATjCJUMcVVESZXJLS",desc:""},
  {name:"Bitfinex",account:"rLW9gnQo7BQhU6igk5keqYnH3TVrCxGRzm",desc:"1"},
  {name:"Bitfinex",account:"rE3hWEGquaixF2XwirNbA1ds4m55LxNZPk",desc:"2"},
  {name:"BitForex",account:"rPSJ1TdurLDkgiptGUgvGii72tWto2cQBA",desc:""},
  {name:"Bitget Global",account:"rGDreBvnHrX1get7na3J4oowN19ny4GzFn",desc:""},
  {name:"BitGo",account:"rD4G6gtD2KwHqsRf7pcyA8r1neUzXT61ix",desc:"Custody"},
  {name:"Bithomp",account:"rhUYLd2aUiUVYkBZYwTc5RYgCAbNHAwkeZ",desc:""},
  {name:"Bithomp",account:"rBithompKtixswR4bknJqYaxnm7yRhGYFq",desc:"ID"},
  {name:"Bithumb",account:"rPMM1dRp7taeRkbT74Smx2a25kTAHdr4N5",desc:"1"},
  {name:"Bithumb",account:"rNTkgxs5WG5mU5Sz26YoDVrHim5Y5ohC7",desc:"2"},
  {name:"Bithumb",account:"rD7XQw67JWBXuo2WPX2gZRsGKNsDUGTbx5",desc:"3"},
  {name:"Bitinka",account:"rGDDcePmKQHx51UKPYQJWhq3YCnqNyrzG2",desc:""},
  {name:"BITKER",account:"rWKvxVJJdBUpM3wW68Ah1Ene4P7UvwymH",desc:"1"},
  {name:"BITKER",account:"rLd6nVZbTy6FE9Dfh5MmJWWFaR65CgFcfs",desc:"2"},
  {name:"Bitladon",account:"rDgP14awuo2bGhmdMRbBaJRp1dVMM1pCvK",desc:""},
  {name:"Bitlish",account:"rBJYrEtydZHnvrJuTXLZweMEECgw6b8PEz",desc:""},
  {name:"BitMarket",account:"rD27FeV6FivcWwpSwdRjEXduBXytnn72Mx",desc:"1"},
  {name:"BitMarket",account:"rGKvkZrEczFrVPvFqEkfUW1pjcRimN4uWL",desc:"2"},
  {name:"BitMarket",account:"rHBaA51ytgay6J93kWWhsYWMCDLyymtd46",desc:"Cold"},
  {name:"BitMart",account:"rEpNmrCTsxnNnE9BYEcHB94QM4KiRdDepy",desc:""},
  {name:"BitMax",account:"rpinhtY4p35bPmVXPbfWRUtZ1w1K1gYShB",desc:""},
  {name:"BitMesh",account:"r3R49PvebowowBJYZvWiDXfMnMnJ7VHx5g",desc:"1"},
  {name:"BitMesh",account:"rEj46A83qoqQXddgiKdFbL1pBss9p8um6z",desc:"2"},
  {name:"BitNaru",account:"rntpaurz3rg1DjKsrPsWnppv63RvB17MQz",desc:"1"},
  {name:"BitNaru",account:"rNQgk5fncvu3Zre1MXp6ZUZSGGnhMESvbf",desc:"2"},
  {name:"Bitnovo",account:"rLVoKJ8UMHntdq3oBD4dGUKf7aMAE8SjFa",desc:""},
  {name:"BitoPro",account:"rPHYZy1UMQ3LyWednTdyhRpBKSFwRB72qZ",desc:"1"},
  {name:"BitoPro",account:"rJvBpqnsi3VGFnoJLjK9HysEzXn8ykYZ2w",desc:"2"},
  {name:"Bitpanda",account:"rUEfYyerfok6Yo38tTTTZKeRefNh9iB1Bd",desc:"1"},
  {name:"Bitpanda",account:"rhVWrjB9EGDeK4zuJ1x2KXSjjSpsDQSaU6",desc:"2"},
  {name:"BITPoint APEC",account:"rwCvyTm1Geb3xjB5sDZcg7gKWzQDBzwXYV",desc:""},
  {name:"Bitrota",account:"r3TUjts6GFTbdZ3wnCv1DbiQUGF9xrH5EP",desc:""},
  {name:"Bitrue",account:"raLPjTYeGezfdb6crXZzcC8RkLBEwbBHJ5",desc:""},
  {name:"Bitrue",account:"rNrFVnR47ZinYNBGtrbk8Xcgp2FHkGfDYi",desc:"Cold"},
  {name:"Bitrue",account:"rfKsmLP6sTfVGDvga6rW6XbmSFUzc3G9f3",desc:"3"},
  {name:"Bitsane",account:"rGTFFFJB3iPJEitfTrZeht7Dr4VAnjQ9m",desc:""},
  {name:"Bitsdaq",account:"rNh4YSHxzuPb3QhcV7EWime6Jc5C8YcRYH",desc:""},
  {name:"Bitsler",account:"rsekGH9p9neiPxym2TMJhqaCzHFuokenTU",desc:""},
  {name:"Bitso",account:"rfEu1Wnr7LxStoFx8DBdzgr8M16FBUbH3K",desc:"1"},
  {name:"Bitso",account:"rLSn6Z3T8uCxbcd1oxwfGQN1Fdn5CyGujK",desc:"2"},
  {name:"Bitstamp",account:"rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv",desc:"1"},
  {name:"Bitstamp",account:"rUobSiUpYH2S97Mgb4E7b7HuzQj2uzZ3aD",desc:"2"},
  {name:"Bitstamp",account:"rGFuMiw48HdbnrUbkRYuitXTmfrDBNTCnX",desc:"Hot"},
  {name:"Bittrex",account:"rPVMhWBsfF9iMXYj3aAzJVkPDTFNSyWdKy",desc:""},
  {name:"Bitvo",account:"rUR1aPYTUxmCqSxkpRHUTqUTPVDY2z1MG1",desc:"1"},
  {name:"Bitvo",account:"rKQ9PxEpCH6pQKATbC6xC6asfwiMfUxyAc",desc:"2"},
  {name:"Bitvolo",account:"rKmcNCNmMduaz9NeR6ifQ3TjyqfYfUJS58",desc:"test"},
  {name:"Bit-Z",account:"rs8ec9v3tvpEVFNXyRZXxVPpYnFJCAvr2C",desc:"1"},
  {name:"Bit-Z",account:"rGtW6G759bNNS72QKazhuVoEY16rPot9EG",desc:"2"},
  {name:"Bitzon",account:"rnHf7TFhZdBBKay5rLoKFmysk1GvxgK21a",desc:""},
  {name:"Blocktrade",account:"rLgKr79aQWaiRNzEoMDbvT57E6UPQ3d7HS",desc:"1"},
  {name:"Blocktrade",account:"rEMcmYrJ7yYFyXptmzTQQpXRas1uGDu7Vc",desc:"2"},
  {name:"BTC-Alpha",account:"rKSQCwRuHqL8GgRtutBGnEmhaAxpUaQA1V",desc:""},
  {name:"BTCEXA",account:"rQG4ZpBaeGjmTTCMJf6NGGS74p3Epkar7Z",desc:"1"},
  {name:"BTCEXA",account:"rL7SppLcU9oDRUxKRoLhz1DtTbQZbVM9nS",desc:"2"},
  {name:"BTCexchange",account:"r3S9W2pYZj7vBueA8scxdJBSEVU2wjMedB",desc:""},
  {name:"BTC Trade UA",account:"rpd6t1Z7o4ME2jgzhfBjYUwhpEcBnZufGG",desc:""},
  {name:"BTC Markets",account:"r94JFtstbXmyG21h3RHKcNfkAHxAQ6HSGC",desc:"1"},
  {name:"BTC Markets",account:"rL3ggCUKaiR1iywkGW6PACbn3Y8g5edWiY",desc:"2"},
  {name:"BTC Markets",account:"rU7xJs7QmjbiyxpEozNYUFQxaRD5kueY7z",desc:"3"},
  {name:"BtcTurk",account:"rNEygqkMv4Vnj8M2eWnYT1TDnV1Sc1X5SN",desc:"1"},
  {name:"BtcTurk",account:"rGmmsmyspyPsuBT4L5pLvAqTjxYqaFq4U5",desc:"2"},
  {name:"BW",account:"r4hYwnBsNH764iTfhRSopu4M3Ct5gMkCGD",desc:"1"},
  {name:"BX.in.th",account:"rp7Fq2NQVRJxQJvUZ4o8ZzsTSocvgYoBbs",desc:""},
  {name:"C2CX",account:"r3UAzAd2KWqoHFF8GXwohfrSYgf3BrbmHD",desc:""},
  {name:"Catex",account:"rp953pKrFqc8NLa2z5dqcpgh6z4ZdBskPp",desc:""},
  {name:"CBANX",account:"rQ3fpcjYAptbLQ88VdiAkQ8VwJJYeYtyKa",desc:""},
  {name:"Celsius Network",account:"rH9gMu9GrwpCJV8EqcYs92FQvh8D77sDXk",desc:"1"},
  {name:"Celsius Network",account:"rMBvfycdzba3Ven9UGG5mrEtG5SNDZR3vf",desc:"2"},
  {name:"Celsius Network",account:"rNJ4rRvx8AL7KBRCAxJjhqfUGZMtL5eDpV",desc:"3"},
  {name:"CEX.IO",account:"rE1sdh25BJQ3qFwngiTBwaq3zPGGYcrjp1",desc:""},
  {name:"ChainEX",account:"rKCAwydpMNguTqMhoLM8THMkC9Ujp8PtY8",desc:""},
  {name:"ChangeNOW",account:"r9Be4diPqGucdPNPvzY1rFTTATLFhFeKSF",desc:""},
  {name:"COBINHOOD",account:"rJNgiY6shrnWav6Sv2nmsyzNJoKzBGg6X8",desc:""},
  {name:"CODEX",account:"r9QrNnxjwDbvX2b4UwmZojtXh9i3eLrYK9",desc:"1"},
  {name:"Codius Hosts",account:"rHAyWHuM66Q4FbHT6iHdEHqVXqmTmXQKHa",desc:""},
  {name:"Coinbase",account:"rLNaPoKeeBjZe2qs6x52yVPZpZ8td4dc6w",desc:"1"},
  {name:"Coinbase",account:"rw2ciyaNshpHe7bCHo4bRWq6pqqynnWKQg",desc:"2"},
  {name:"Coinbe",account:"rNA8ctDXygrUUESSeZCkwUG8jKhmYX4uD1",desc:"1"},
  {name:"Coinbe",account:"rDVUNNucFu2PNzkNr2BBiRaaDtpCbjuCkF",desc:"2"},
  {name:"CoinBene",account:"r9CcrhpV7kMcTu1SosKaY8Pq9g5XiiHLvS",desc:""},
  {name:"Coincheck",account:"rNQEMJA4PsoSrZRn9J6RajAYhcDzzhf8ok",desc:"1"},
  {name:"Coincheck",account:"rwgvfze315jjAAxT2TyyDqAPzL68HpAp6v",desc:"2"},
  {name:"CoinDCX",account:"raSLkv529QyqKAPLK1z3mDsNa8a6RLt2ok",desc:""},
  {name:"Coindelta",account:"r9QA3mVFQ7V4CE8uGVaeGGDGgeAFc8rsPF",desc:""},
  {name:"Coindirect",account:"rPz9MAKN1k6h1rXYBfCS88j6muLgppJu1i",desc:""},
  {name:"CoinEx",account:"rDt7d2bf2CSKzTFug2etkhbr8yQjbZtLE7",desc:""},
  {name:"CoinFalcon",account:"r9kEw2Q5taewopSVpdagECb9QbEMayRxe4",desc:""},
  {name:"CoinField",account:"rK7D3QnTrYdkp1fGKKzHFNXZpqN8dUCfaf",desc:""},
  {name:"CoinFlux",account:"raHDzTKRoed9Zy1k82PcFTjTEVe9qfvkMd",desc:"1"},
  {name:"CoinFlux",account:"rLww8GQYbZuzWt47AhwQDVmrzuo5peg1hs",desc:"2"},
  {name:"CoinGate",account:"rPyFs5kpbiiawSdP9JGdaYM33zfUUah1TY",desc:""},
  {name:"Coinhako",account:"rDCWkSuwrXPffeX2YgSuV7uRgDfUwi9PVi",desc:"1"},
  {name:"Coinhako",account:"r4ep6pSY9JhMhLHGFb5GtVabzS1KvihiZP",desc:"2"},
  {name:"CoinHe",account:"rU3UP3xcTn76GQfxV93gBguvQqa7vd41BT",desc:""},
  {name:"CoinSwitch",account:"rMvo4VQoutQm3P1eMXghcXrTdHNxxUTU3X",desc:""},
  {name:"CoinJar",account:"rPvKH3CoiKnne5wAYphhsWgqAEMf1tRAE7",desc:""},
  {name:"Coinmate",account:"rpWfoKdTix79eKWHHkPT8TqbA2bTBk9GLc",desc:""},
  {name:"CoinMex",account:"rftJisbPUda6vDmzvGQES4e5Qbc5BvZuFh",desc:""},
  {name:"Coinmotion",account:"rLrbZMJDdL8eQd7HsW314bCtvE16LTLYkM",desc:""},
  {name:"Coinome",account:"rNaDaYdJDa1bsWHnEm1dZd9Yc6Vs1KHRTE",desc:"1"},
  {name:"Coinome",account:"rUqimim3skp7X3kjmg4Ev1UvsjZrGJ6s1c",desc:"2"},
  {name:"Coinone",account:"rp2diYfVtpbgEMyaoWnuaWgFCAkqCAEg28",desc:"1"},
  {name:"Coinone",account:"rPsmHDMkheWZvbAkTA8A9bVnUdadPn7XBK",desc:"2"},
  {name:"CoinPayments",account:"rCoinaUERUrXb1aA7dJu8qRcmvPNiKS3d",desc:""},
  {name:"CoinPlug",account:"rp1FYC5ggnv2eRPF86Z3ywKacxvAceS3kg",desc:""},
  {name:"CoinsBank",account:"rhvXPd5koNrifWhwhReKJvapd2ihbCewE3",desc:""},
  {name:"CoinSmart",account:"rNoGCWqvtXSjZ2FTSVRb144HZVB2LYZWKt",desc:"1"},
  {name:"CoinSmart",account:"rBsHpScdJrctoiYEtzs6oEc4Vw44by44bV",desc:"2"},
  {name:"Coins.ph",account:"rU2mEJSLqBRkYLVTv55rFTgQajkLTnT6mA",desc:""},
  {name:"Coinsuper",account:"r33A7DdKzxenN7dNowJhXDhpr5y5H8CnBT",desc:"1"},
  {name:"Coinsuper",account:"rhSxhgzMUhvk8iRg4m9XHbcHWgNDR89Cv7",desc:"2"},
  {name:"CoinTiger",account:"rsbKKCAQZPa3Xxqz4GuPBSsZh59ZEZ6VMf",desc:""},
  {name:"Coinvest Plus",account:"rBNtMHAP8u9UkbkRb1JDiPE8TjHKhehSxZ",desc:"1"},
  {name:"Coinvest Plus",account:"rPL7xQ4eDhT3ZMJWeQnDATe2Jb8F4QPYpC",desc:"2"},
  {name:"CoinZark",account:"rPutbNse6NJpmeevTyhVbtx29BwCE12D8Z",desc:""},
  {name:"COINZEUS",account:"rsbyjybmsd86vUDhQAhmnjfQ8PfyttLSLs",desc:"1"},
  {name:"COINZEUS",account:"rhTzkEApLxTir1igxuuYoaVQ3k12yH3hwp",desc:"2"},
  {name:"COINZEUS",account:"rp1kF6QwzQJ7ZgKyMRyVm2jvPtyGLbctmt",desc:"3"},
  {name:"coinzo",account:"rDQGVYCKC3StBmJV6my9uL1Dn9q7TzEGqS",desc:""},
  {name:"Computing for Good",account:"rNKXT1p7jpt5WxSRSzmUV6ZB6kY7jdqHmx",desc:"Giveaway"},
  {name:"COSS",account:"rHW5SNb4JUaedGuVc2MoHUFUmX4kXEws9p",desc:"1"},
  {name:"COSS",account:"rpTgBeQcJUHzCWgdyLYS57h2WUSUqW4A7W",desc:"2"},
  {name:"CredoEx",account:"rGFvYGUfS44hm4sSSibjb8UAo6VkK4m54A",desc:"BitBounce"},
  {name:"Crex 24",account:"rLZh28YgxC712oPJYjYvU6Wa8146ycxkBM",desc:""},
  {name:"CryptoBridge",account:"rGgP9356daGzSYeRpnbATakrHc3ejAxuaP",desc:"DEX"},
  {name:"Crypto Harbor",account:"rHTiH3epXBaAfGZCubsWEVSc2ku96xSKVG",desc:""},
  {name:"Cryptokart",account:"rhEjZdaSyepzbT5d8JerB6vdRu42ti7Sh6",desc:""},
  {name:"Cryptology",account:"rh9R3XsHVsKGU9RE2JKwoi3eyKUWWvMZeb",desc:"1"},
  {name:"Cryptology",account:"rKPsKrX1LWyDGqARPwzq36pcRo8sMNUNvV",desc:"2"},
  {name:"Cryptosa",account:"r3QdQboXNKc5ahNMVd2EJ2mH2nAtaLLC7o",desc:""},
  {name:"Cryptsy",account:"rJGW69cMpaSqNwjhWjvtkRwhvm9yNfnNpN",desc:""},
  {name:"CyberBTC",account:"r4FhxAcdu5UPiFY5FSYtrEKigHdcSysRdu",desc:""},
  {name:"Darb Finance",account:"rhQPTmLNSFSaaAJnJUvdt3m1DS8XRw42qm",desc:""},
  {name:"DCEX",account:"r9W22DnkmktvdSdsdWS5CXJAxfWVRtbDD9",desc:"1"},
  {name:"DCEX",account:"rHXvKUCTzsu2CB8Y5tydaG7B2ABc4CCBYz",desc:"2"},
  {name:"Dcoin",account:"rLW9fNRyv6pxz6Skr8BsCP7PEWNG3vUvLT",desc:""},
  {name:"DeCurret",account:"rfhpLiK85o7JTooxTgwzGheHqnEB9Q7Brt",desc:"1"},
  {name:"DeCurret",account:"rhSArgLVVhmQ9Qw2vGJ294YrpyZjpKhNVW",desc:"2"},
  {name:"DeCurret",account:"rLnZnFRVKsxRVbXmF8CYHgj8VA5mhRASq2",desc:"3"},
  {name:"DeCurret",account:"rswHhsqEiSoxQ4ZMh2DGNJGueiR23mkf37",desc:"4"},
  {name:"DigiFinex",account:"rnG2XVwdULE5mfWA5EFxnyTkUGgg2K39AP",desc:""},
  {name:"Dipbit",account:"rMqP6R2nku9UiDfVzYMkpKzrEqiWUsT5m6",desc:""},
  {name:"Donocle",account:"rHNJTYYVKCgySmF6F8AYSRX2f9q7Vq5Yid",desc:""},
  {name:"DragonEx",account:"rhCaNjw1B7m1aupE5Xtdn5V87bDmeeEuvD",desc:""},
  {name:"DuckDice",account:"rHaEgsbEC1uq6spFjoonirz98yaDeokhzU",desc:""},
  {name:"DX.Exchange",account:"r9U6UPU2S2aWC7uiKPjiyV37evWwPVqdTj",desc:""},
  {name:"Einstein Exchange",account:"rhaTm3xhTCc1bxE9XTVrQfbASRGp4JGUUk",desc:"1"},
  {name:"Einstein Exchange",account:"rHgQvW5yVURn2zN816frxwEhamLHYPdvEV",desc:"2"},
  {name:"EO.Trade",account:"rwHq5GijQSui8Zis7ndRDXpMnReeyHVyHo",desc:"1"},
  {name:"EO.Trade",account:"rwWiEd4Ckzb1QL9XKz1CoJNQBRj4eTRxAC",desc:"2"},
  {name:"Eobot",account:"rB1za2ZVgDnNB7u8LbVN61k5nCByBUtXCA",desc:"1"},
  {name:"Eobot",account:"rGT84ryubURwFMmiJChRbWUg9iQY18VGuQ",desc:"2"},
  {name:"Funding",account:"rwiEtsEY8YRxgHQgvWXsxyUBSZzTMqL2EX",desc:"xrpl-labs.com"},
  {name:"Gate",account:"rHcFoo6a9qT5NHiVn1THQRhsEGcxtYCV4d",desc:""},
  {name:"GDAC",account:"rfD4oqVbGNEkrtkWS39Epo1t5DH42KMSwp",desc:""},
  {name:"GloBee",account:"rfF9CCnrYitv8dKonkqDqqcHLCPJ9JPvA",desc:"1"},
  {name:"GloBee",account:"rw2sz65R1ZRaPWKVytJSdHg6nCfuSBRWSq",desc:"2"},
  {name:"Gobaba",account:"rJdhqjuPKNvYb82CGYdhXrEAfkqbeRzaBY",desc:""},
  {name:"GOEX",account:"rJWmcHHjFJatBEQd3R6B6rE3WvSpxCiTpP",desc:""},
  {name:"GOPAX",account:"rwSdwXsQVCjYXUyempsGxk1Sgws6perYZL",desc:""},
  {name:"Grand Capital",account:"rD9cfNHkLDaFMQobzHjACJUSWZDKZFj2fs",desc:""},
  {name:"HitBTC",account:"r4eEbLKZGbVSBHnSUBZW8i5XaMjGLdqT4a",desc:"1"},
  {name:"HitBTC",account:"rhL5Va5tDbUUuozS9isvEuv7Uk1uuJaY1T",desc:"2"},
  {name:"HitBTC",account:"rNUyxNugxv67vhQZZCif2Ru1Hb4APNmwUS",desc:"3"},
  {name:"HitBTC",account:"rLCmrXtyLNSma1g4YPpnwWF664zGaUhMc8",desc:"4"},
  {name:"HitBTC",account:"rwpMvfxoodXggJ1g4qv6MWAPQqWDwQyHUW",desc:"5"},
  {name:"Happy Kids Dirty Hands",account:"rwNyRPLgm86FnzZDgJzikb5buybWqVNhJt",desc:"Cold"},
  {name:"HODL Finance",account:"rawqXp4MnEbwLE99DUdB8L1TTPpNjPER2W",desc:""},
  {name:"Hotbit",account:"rGzqpy3BaFNcXXqYsKAhFp4HNJGnLFZdnb",desc:""},
  {name:"Huobi Global",account:"rKoFoX8RveEMP5MgrbKA8R8J7nFi9g2zW4",desc:"1"},
  {name:"Huobi Global",account:"rfexLLNpC6dqyLagjV439EyvfqdYNHsWSH",desc:"2"},
  {name:"iCoinbay",account:"rHaPdopD7SBDrjo37XxwB5QW3EKdYcVu3e",desc:""},
  {name:"IDAX",account:"rG6rxRpkPyi954utDwymA2sc1i9j3VjWkv",desc:"1"},
  {name:"IDAX",account:"rhEYk3yCboeYq9HvnjGALR2aQFQnqaMZSS",desc:"2"},
  {name:"imove",account:"rHgmYukwN1LMHRqAoavSLheks8XXhxgxBH",desc:""},
  {name:"Independent Reserve",account:"r33hypJXDs47LVpmvta7hMW9pR8DYeBtkW",desc:""},
  {name:"Indodax",account:"rwWr7KUZ3ZFwzgaDGjKBysADByzxvohQ3C",desc:""},
  {name:"Instant Bitex",account:"ra8F9YRetgTPP6WXfKdR9w3bNZEVpNpMfM",desc:""},
  {name:"Instanz",account:"r972cb9cy3Ca4pbEt7MsMvAiPasVYgP2t5",desc:""},
  {name:"Internet Archive",account:"rGeyCsqc6vKXuyTGF39WJxmTRemoV3c97h",desc:"1"},
  {name:"Koineks",account:"rpVTz6jPYE3HbXX7RmCUMCirBYcfJU2q4j",desc:"1"},
  {name:"Koineks",account:"ryBANkk28Mj71jRKAkt13U1X9ubztsGWZ",desc:"2"},
  {name:"Koinex",account:"rLdinLq5CJood9wdjY9ZCdgycK8KGevkUj",desc:"1"},
  {name:"Koinex",account:"rGhssiAZkbAGyHVxEmQuJD1QWs9aDyaB6i",desc:"2"},
  {name:"Korbit",account:"rBTjeJu1Rvnbq476Y7PDnvnXUeERV9CxEQ",desc:""},
  {name:"Kraken",account:"rLHzPsX6oXkzU2qL12kHCH8G8cnZv1rBJh",desc:""},
  {name:"Kryptono",account:"rPvTjC1LXsWtt1Rv3CFVWvedqfkryiJSxg",desc:"1"},
  {name:"Kryptono",account:"rhj9VJ5aE3hAbk23mgpH1PwdCYcUexqokb",desc:"2"},
  {name:"KuCoin",account:"rUW9toSjQkLY6EspdnBJP2paG4hWKmNbMh",desc:"1"},
  {name:"KuCoin",account:"r4pxv9txfQTyVkQUetNmyJqDy7s5fPPVfB",desc:"2"},
  {name:"KuCoin",account:"rhKrvXY8zRvVyDLT4nfXB86HyhqQyvcr4c",desc:"3"},
  {name:"Kuna",account:"rMtb2JEX8xmcgSKxCB7aZPDyzyVhbM2RzV",desc:""},
  {name:"LakeBTC",account:"rHcajWQJmM2MejujoSog5yeQGurN84DPAJ",desc:""},
  {name:"Lazur",account:"rPwBYEh4EtJxeSq9XeKyEjdGEZYMv6wAiC",desc:""},
  {name:"LBX",account:"r4E49HU6CTHyYMmsYt3F1ar1q5W89t3hfQ",desc:""},
  {name:"Liquid",account:"rHQ6kEtVUPk6mK9XKnjRoudenoHzJ8ZL9p",desc:""},
  {name:"LiveCoin",account:"r4zsY82bVippLpS7K7ru5xUReyvX1JQktX",desc:""},
  {name:"LuckyFish",account:"rQL3rmtijDT33ytPXdJd41bG3Rpa2ZyfqN",desc:""},
  {name:"Luckygames",account:"rK7LSKygRUu9y9xcuhkWbcMRKRF5HVWwVL",desc:""},
  {name:"MAX Exchange",account:"rMZdHB6uHvAEPzzKdsWYyhgyLkhFNjuwih",desc:""},
  {name:"MBAex",account:"rUhZf2mksmqXi5dD9BCPdtBYu8gZ7FejUV",desc:"1"},
  {name:"MoneyToken",account:"r48ur7yUTnDU5kTZ3jQLWhED8nWLLM3AWH",desc:""},
  {name:"MoonTrade",account:"rNriUSXDqVGWkdmFc2oADKqKLy4G2p85Fq",desc:""},
  {name:"Mundax",account:"rEsbmFwZaqBiKTZdXA6inK2GwXVXvp736u",desc:"1"},
  {name:"Mundax",account:"rHbQDDU7QFnQ3isWtMYzPaURGkC2E9Wbb7",desc:"2"},
  {name:"Mundax",account:"rJcjTsFXgM5uMhBUJPfjTknknwjbXxsob",desc:"3"},
  {name:"NAGA",account:"rG5p7nE9fYojqRGUNbDjq1ypMhLraGC3oh",desc:"1"},
  {name:"NAGA",account:"rNAGAiqt68FfToorehrYAZZyQiZ2QdCSrD",desc:"2"},
  {name:"Nexo",account:"rwADc5YVbAfDmRyjbqPoG48H5jmnbD2xV5",desc:"1"},
  {name:"Nexo",account:"rnuPTVikw8HKK4hBGCtnq2J2433VYaZPZQ",desc:"2"},
  {name:"NLexch",account:"rDSY2gUCDqCYdtAPms8kz4ZSJiTnZQ6TvM",desc:""},
  {name:"Nobitex",account:"rwRmyGRoJkHKtojaC8SH2wxsnB2q3yNopB",desc:""},
  {name:"Nuex",account:"rEgs9hHVws4hDREGGEAu4i4SbggAEw6gBm",desc:""},
  {name:"NuMoney",account:"rDnhaeLUhYGViyCrGRUVezkUyR1kMEEbt7",desc:""},
  {name:"OKX",account:"rUzWJkXyEtT8ekSSxkBYPqCvHpngcy6Fks",desc:""},
  {name:"OMGFIN",account:"rQafLzuWB4PQYAaAuZ3FLBVi1iuGvx9uBN",desc:""},
  {name:"OOOBTC",account:"rL1vJjoQfKhfCYUXHdAqXYVUaoU59adV22",desc:""},
  {name:"OpenLedger",account:"rNEn8kHBkNWf85CQaZhpJvkkYaZYHcLuUT",desc:"DEX"},
  {name:"Orionx",account:"rhQrkgoV4uza557mW6HbBWMtTDkB7u5yrs",desc:""},
  {name:"OTCBTC",account:"r4YC1aD49aHtm33Az1vxhfBbLp3VCkvEuT",desc:""},
  {name:"Ovis",account:"r4vBYmqhdkXBNRPnvAn5boZSPfWB95eWmZ",desc:""},
  {name:"Palmex",account:"rBCC5xrxtNaepXFUuYhhuga5ez1zJnMW9E",desc:""},
  {name:"Paribu",account:"rKdDdrbU3MedsG7VtBAir4RjC35tzjDZnr",desc:""},
  {name:"PayBis",account:"rKT1BPiQ2t1qsPUX5jg3ZPZNWMZoQw2fm6",desc:""},
  {name:"PayKassa",account:"rP8VvqTDeMtC7Vmp85CVvqJ5BH1QF3yvj3",desc:""},
  {name:"PHOBOS Platform",account:"ra5ER42K37opCxDq1Tre3Pd4oRVbncosoL",desc:""},
  {name:"PLAAK",account:"rL1kgDqaQSvoxjTt8ibAi7T4rEKP7pS9ei",desc:""},
  {name:"Poloniex",account:"rDCgaaSBAWYfsxUYhCk1n26Na7x8PQGmkq",desc:""},
  {name:"Polyx",account:"rUbPReuLqkRdjx3RQFZ6JaEBtCNZgX5JhT",desc:""},
  {name:"Private Internet Access",account:"r9EUYx41zx3audeARUwpkDF7VuwcmbwYTU",desc:""},
  {name:"ProBit",account:"rJChk8e71gxVhyJSr1srzZxWhVisWMMYKZ",desc:"1"},
  {name:"ProBit",account:"rsA9ijHjo7hAkitc9GsXsiwXzqGs7eoeqr",desc:"2"},
  {name:"Purcow",account:"rDajxunnyYo7pGbFFfkQdPpenoQPYUEg2d",desc:""},
  {name:"Quidax",account:"rBwdSqfFMBYUazUsv9pV1ZpHTG2nZcaNJv",desc:"1"},
  {name:"Quidax",account:"rnNQs4WAKUHes7kJtqqRiU3Wq9q1pHuDEt",desc:"2"},
  {name:"Remitano",account:"rLpumSZQNJ6Cve7hfQcdkG9rJbJhkSV8AD",desc:""},
  {name:"Rfinex",account:"rfLFX6mhkWGZDumv6km14N9RbyWtFvdyGC",desc:""},
  {name:"RightBTC",account:"rGNmVMG9KwVf9XvfNuEHb2dRLNhJqa6BFD",desc:"1"},
  {name:"RightBTC",account:"rPks48owYx8VfLcXQ4qBKNhFGKxe5Z9sPC",desc:"2"},
  {name:"Ripple",account:"r3kmLJN5D28dHuH8vZNUZpMC43pEHpaocV",desc:""},
  {name:"rippleitin.nz",account:"rEE1JVZrpEjgZibGddhVv4ESmFpcxnjNUv",desc:""},
  {name:"SecondBTC",account:"rw1NMXosYqooC4J8UGsA5neKnTLa7CrNqb",desc:""},
  {name:"ShapeShift",account:"rwfGzgd4bUStS9gA5xUhCmg1J86TMtmGMo",desc:""},
  {name:"SistemKoin",account:"rf4wZgPXBB2j7PWnsuFhkuidmTN75ZnudP",desc:""},
  {name:"Stellarport",account:"rJY2W6QRaqbcmnYdzG3qdK1kYz5Ww6tXVk",desc:""},
  {name:"STEX",account:"rUh9cVv8FWE6LmJaCz5MEinGEN2GovcZaa",desc:""},
  {name:"Stronghold",account:"r4qj7xd6eJDt6Jv7VVXZ2mLGDpMyiQz8i3",desc:""},
  {name:"The XRP Effect",account:"ramfp11hEeE6oGjHoAU94Uh1ma3hAMEU3c",desc:""},
  {name:"Toast Wallet",account:"rToastMYRQh8boeo5Ys1CnPySmt3c9x3Y",desc:""},
  {name:"Tok",account:"rGueyQFkj4XT74wfpCqasTACo6FBQfjwCx",desc:"1"},
  {name:"Tok",account:"rQrE1mAKBHy2BDjBXze1kLHMNxfpf31kc",desc:"2"},
  {name:"Tokens",account:"rPkitTzAi3KahtGAbdCuq3XxZtDjRCG3U8",desc:""},
  {name:"Tokocrypto",account:"rBg33rYWkR9G2jDKZKmCsGd1wZrGoL83Lb",desc:""},
  {name:"TradeSatoshi",account:"r9VoqvUwZipzbVfMXzDkSBvdv38CapKywg",desc:""},
  {name:"Triple Dice Exchange",account:"rUjxty1WWLwX1evhKf3C2XNZDMcXEZ9ToJ",desc:"1"},
  {name:"Triple Dice Exchange",account:"rpiWoLNdX6KLrM66Hzp71gLc6vwYVgXVXL",desc:"2"},
  {name:"Triple Dice Exchange",account:"rMYYUjFAxqkyKzyXkYNG2K5H7pESUri4t3",desc:"3"},
  {name:"Unodax",account:"rLLGjxCdTKRMBSSC6ELAKq9NPrGEipkeGH",desc:"1"},
  {name:"Unodax",account:"rNEWtRNMMwsdky5Lu7wkzFMYwiiVxaz6SG",desc:"2"},
  {name:"UPbit",account:"rNzT5xopUaJK8L7mHbThUGKaHoct62dNBC",desc:"1"},
  {name:"UPbit",account:"rN9qNpgnBaZwqCg8CvUZRPqCcPPY7wfWep",desc:"2"},
  {name:"Uphold",account:"rKfzfrk1RsUxWmHimWyNwk8AoWHoFneu4m",desc:"1"},
  {name:"Uphold",account:"rQrQMKhcw3WnptGeWiYSwX5Tz3otyJqPnq",desc:"2"},
  {name:"ValueBit",account:"rpyXM7w2zYX53yNK25wQz4sZsjqC23Ckdr",desc:""},
  {name:"Vebitcoin",account:"rNbxjMxewgMQCc4TFF2yYwBoVbCCbhZF5c",desc:"1"},
  {name:"Vebitcoin",account:"r48kptkxw5gCs2bNBPVdC93ytWqYw7xX5Q",desc:"2"},
  {name:"VELIC",account:"rLfm8tMVfpsjE5wNaA2zMARtMCVXAXhhia",desc:""},
  {name:"WazirX",account:"rwuAm7XdcP3SBwgJrVthCvCzU7kETJUUit",desc:"1"},
  {name:"WazirX",account:"rJXcrnAS8XoBwjvd5VrShrLMY8buPuiuC5",desc:"2"},
  {name:"WietseWind",account:"rpePPeRpC89vpCY3CDzhzMCs78nPoNnAKm",desc:""},
  {name:"Willow House",account:"rDDKHn5bFWoZnMFpzPzGBamC42oU9NJPUB",desc:""},
  {name:"Wipple",account:"rhkvfNv6tzh6CMfpXZdX2t7HGN2ZX46Tco",desc:""},
  {name:"Wirex",account:"rXieaAC3nevTKgVu2SYoShjTCS2Tfczqx",desc:"1"},
  {name:"Wirex",account:"rfkH7EuS1XcSkB9pocy1R6T8F4CsNYixYU",desc:"2"},
  {name:"Worldcore",account:"rnRGWUhwZrGkSxGoPfTTMFwZhDiPyySWVD",desc:""},
  {name:"XCOEX",account:"rDgnUtf2ECr7XrczPZ1bivhDiqRCy2fvoR",desc:""},
  {name:"XCH4NGE",account:"rsA8rKzZhdAoKDATLLcsGuygyJ1F9JtVqV",desc:"1"},
  {name:"XCH4NGE",account:"rLwXw272jVgtk1Ar5EdnrZULKaKQCWAenQ",desc:"2"},
  {name:"xCrypto🚀Crash",account:"rK9dBkad6fQ2qkvCJuyCqCGQrcF1fLhoA9",desc:""},
  {name:"XRParrot",account:"rp65fD8N8fWxhMXwQN1CYVwYPeVofmh3S1",desc:""},
  {name:"XRP Community Fund",account:"rpEPpEr5ED6NzykYunBEJJoMdfjp1t3uf4",desc:""},
  {name:"XRP Scan",account:"rscanPocB2DeRgLUD6S3vhZjeaQ4h21c9j",desc:""},
  {name:"XRP Text",account:"rQHYSEyxX3GKK3F6sXRvdd2NHhUqaxtC6F",desc:"SMS"},
  {name:"XRP Text",account:"rNEtcAT7zRFd2MXc38ja4ng3ddEVkk22Ax",desc:"Telegram"},
  {name:"XRP Tip Bot",account:"rPEPPER7kfTD9w2To4CQk6UCfuHM9c6GDY",desc:""},
  {name:"XRP United",account:"rJY2KYfzkrWKikHnhH45d5n2YJHSKbTp2o",desc:"1"},
  {name:"XRP United",account:"r3HrZu2zweSjb7s3ZYHbB4C8UtBf1E59m1",desc:"2"},
  {name:"XRP United",account:"rHYJuExR1TDVAKj4cd7tyDntaXR7zoz6ch",desc:"3"},
  {name:"Yobit",account:"rPBMDP7CGiKzMvPx6SsCGgeDsrsUyv1K1b",desc:""},
  {name:"YouHodler",account:"rDhmyBh4JwDAtXyRZDarNgg52UcLLRoGje",desc:""},
  {name:"Zipmex",account:"rpwx6G3Dd1uziyZBw3s9s3aMenmdhTDdss",desc:"1"},
  {name:"Zipmex",account:"rpoSVDeHqAc16TxKGz5efLZg6Z9BQqmcCW",desc:"2"}
];

